// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: api/proto/user.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================
// 🧩 User messages
// ==========================
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ReferrerId    string                 `protobuf:"bytes,4,opt,name=referrer_id,json=referrerId,proto3" json:"referrer_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetReferrerId() string {
	if x != nil {
		return x.ReferrerId
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// Dữ liệu khi client yêu cầu tạo user mới
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ReferrerId    string                 `protobuf:"bytes,4,opt,name=referrer_id,json=referrerId,proto3" json:"referrer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetReferrerId() string {
	if x != nil {
		return x.ReferrerId
	}
	return ""
}

// Yêu cầu lấy thông tin user theo ID
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Yêu cầu cập nhật thông tin user
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// Yêu cầu xóa user theo ID
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Yêu cầu liệt kê danh sách user (có phân trang)
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Phản hồi khi gọi ListUsers
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Yêu cầu lấy danh sách người được giới thiệu bởi một user
type GetReferralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsRequest) Reset() {
	*x = GetReferralsRequest{}
	mi := &file_api_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsRequest) ProtoMessage() {}

func (x *GetReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsRequest.ProtoReflect.Descriptor instead.
func (*GetReferralsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetReferralsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Phản hồi danh sách người được giới thiệu
type GetReferralsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrals     []*User                `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsResponse) Reset() {
	*x = GetReferralsResponse{}
	mi := &file_api_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsResponse) ProtoMessage() {}

func (x *GetReferralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsResponse.ProtoReflect.Descriptor instead.
func (*GetReferralsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetReferralsResponse) GetReferrals() []*User {
	if x != nil {
		return x.Referrals
	}
	return nil
}

// ==========================
// 👑 Admin messages
// ==========================
type AdminMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // today, week, month, year
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminMetricsRequest) Reset() {
	*x = AdminMetricsRequest{}
	mi := &file_api_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMetricsRequest) ProtoMessage() {}

func (x *AdminMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMetricsRequest.ProtoReflect.Descriptor instead.
func (*AdminMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *AdminMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type AdminMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers   int32                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	NewUsersToday int32                  `protobuf:"varint,3,opt,name=new_users_today,json=newUsersToday,proto3" json:"new_users_today,omitempty"`
	ReferralCount int32                  `protobuf:"varint,4,opt,name=referral_count,json=referralCount,proto3" json:"referral_count,omitempty"`
	GrowthRate    float32                `protobuf:"fixed32,5,opt,name=growth_rate,json=growthRate,proto3" json:"growth_rate,omitempty"`
	TimeRange     string                 `protobuf:"bytes,6,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminMetricsResponse) Reset() {
	*x = AdminMetricsResponse{}
	mi := &file_api_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminMetricsResponse) ProtoMessage() {}

func (x *AdminMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminMetricsResponse.ProtoReflect.Descriptor instead.
func (*AdminMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *AdminMetricsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *AdminMetricsResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *AdminMetricsResponse) GetNewUsersToday() int32 {
	if x != nil {
		return x.NewUsersToday
	}
	return 0
}

func (x *AdminMetricsResponse) GetReferralCount() int32 {
	if x != nil {
		return x.ReferralCount
	}
	return 0
}

func (x *AdminMetricsResponse) GetGrowthRate() float32 {
	if x != nil {
		return x.GrowthRate
	}
	return 0
}

func (x *AdminMetricsResponse) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

// Tạo hàng loạt user (Bulk)
type BulkCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*CreateUserRequest   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateRequest) Reset() {
	*x = BulkCreateRequest{}
	mi := &file_api_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateRequest) ProtoMessage() {}

func (x *BulkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *BulkCreateRequest) GetUsers() []*CreateUserRequest {
	if x != nil {
		return x.Users
	}
	return nil
}

type BulkCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateResponse) Reset() {
	*x = BulkCreateResponse{}
	mi := &file_api_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateResponse) ProtoMessage() {}

func (x *BulkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *BulkCreateResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkCreateResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BulkCreateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ==========================
// 🔐 Auth messages
// ==========================
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_api_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *AuthResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ==========================
// 📧 Notification messages
// ==========================
type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_api_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *NotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_user_proto protoreflect.FileDescriptor

const file_api_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xb9\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1f\n" +
	"\vreferrer_id\x18\x04 \x01(\tR\n" +
	"referrerId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\x83\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1f\n" +
	"\vreferrer_id\x18\x04 \x01(\tR\n" +
	"referrerId\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"K\n" +
	"\x11ListUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\".\n" +
	"\x13GetReferralsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x14GetReferralsResponse\x12(\n" +
	"\treferrals\x18\x01 \x03(\v2\n" +
	".user.UserR\treferrals\"4\n" +
	"\x13AdminMetricsRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\"\xe9\x01\n" +
	"\x14AdminMetricsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x05R\vactiveUsers\x12&\n" +
	"\x0fnew_users_today\x18\x03 \x01(\x05R\rnewUsersToday\x12%\n" +
	"\x0ereferral_count\x18\x04 \x01(\x05R\rreferralCount\x12\x1f\n" +
	"\vgrowth_rate\x18\x05 \x01(\x02R\n" +
	"growthRate\x12\x1d\n" +
	"\n" +
	"time_range\x18\x06 \x01(\tR\ttimeRange\"B\n" +
	"\x11BulkCreateRequest\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.user.CreateUserRequestR\x05users\"v\n" +
	"\x12BulkCreateResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"E\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserR\x04user\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"=\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"r\n" +
	"\x13NotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"J\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf0\x02\n" +
	"\vAuthService\x12O\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12X\n" +
	"\rValidateToken\x12\x11.user.AuthRequest\x1a\x12.user.AuthResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/validate\x12_\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x13.user.LoginResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12U\n" +
	"\x06Logout\x12\x13.user.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout2\x9e\x06\n" +
	"\vUserService\x12K\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\n" +
	".user.User\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12G\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12P\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\n" +
	".user.User\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/users/{id}\x12Y\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12S\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12t\n" +
	"\x10GetUserReferrals\x12\x19.user.GetReferralsRequest\x1a\x1a.user.GetReferralsResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/users/{user_id}/referrals\x12g\n" +
	"\x0fGetAdminMetrics\x12\x19.user.AdminMetricsRequest\x1a\x1a.user.AdminMetricsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/admin/metrics\x12c\n" +
	"\x0fBulkCreateUsers\x12\x17.user.BulkCreateRequest\x1a\x18.user.BulkCreateResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/users/bulk\x123\n" +
	"\vExportUsers\x12\x16.user.ListUsersRequest\x1a\n" +
	".user.User0\x012\xfc\x01\n" +
	"\x13NotificationService\x12s\n" +
	"\x10SendWelcomeEmail\x12\x19.user.NotificationRequest\x1a\x1a.user.NotificationResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/notifications/welcome\x12p\n" +
	"\x10SendNotification\x12\x19.user.NotificationRequest\x1a\x1a.user.NotificationResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/notifications/sendB&Z$user-management-grpc/api/proto;protob\x06proto3"

var (
	file_api_proto_user_proto_rawDescOnce sync.Once
	file_api_proto_user_proto_rawDescData []byte
)

func file_api_proto_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_proto_rawDesc), len(file_api_proto_user_proto_rawDesc)))
	})
	return file_api_proto_user_proto_rawDescData
}

var file_api_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.User
	(*CreateUserRequest)(nil),     // 1: user.CreateUserRequest
	(*GetUserRequest)(nil),        // 2: user.GetUserRequest
	(*UpdateUserRequest)(nil),     // 3: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),     // 4: user.DeleteUserRequest
	(*ListUsersRequest)(nil),      // 5: user.ListUsersRequest
	(*ListUsersResponse)(nil),     // 6: user.ListUsersResponse
	(*GetReferralsRequest)(nil),   // 7: user.GetReferralsRequest
	(*GetReferralsResponse)(nil),  // 8: user.GetReferralsResponse
	(*AdminMetricsRequest)(nil),   // 9: user.AdminMetricsRequest
	(*AdminMetricsResponse)(nil),  // 10: user.AdminMetricsResponse
	(*BulkCreateRequest)(nil),     // 11: user.BulkCreateRequest
	(*BulkCreateResponse)(nil),    // 12: user.BulkCreateResponse
	(*LoginRequest)(nil),          // 13: user.LoginRequest
	(*LoginResponse)(nil),         // 14: user.LoginResponse
	(*AuthRequest)(nil),           // 15: user.AuthRequest
	(*AuthResponse)(nil),          // 16: user.AuthResponse
	(*RefreshTokenRequest)(nil),   // 17: user.RefreshTokenRequest
	(*LogoutRequest)(nil),         // 18: user.LogoutRequest
	(*NotificationRequest)(nil),   // 19: user.NotificationRequest
	(*NotificationResponse)(nil),  // 20: user.NotificationResponse
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 22: google.protobuf.Empty
}
var file_api_proto_user_proto_depIdxs = []int32{
	21, // 0: user.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: user.ListUsersResponse.users:type_name -> user.User
	0,  // 2: user.GetReferralsResponse.referrals:type_name -> user.User
	1,  // 3: user.BulkCreateRequest.users:type_name -> user.CreateUserRequest
	0,  // 4: user.LoginResponse.user:type_name -> user.User
	13, // 5: user.AuthService.Login:input_type -> user.LoginRequest
	15, // 6: user.AuthService.ValidateToken:input_type -> user.AuthRequest
	17, // 7: user.AuthService.RefreshToken:input_type -> user.RefreshTokenRequest
	18, // 8: user.AuthService.Logout:input_type -> user.LogoutRequest
	1,  // 9: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	2,  // 10: user.UserService.GetUser:input_type -> user.GetUserRequest
	3,  // 11: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	4,  // 12: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	5,  // 13: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	7,  // 14: user.UserService.GetUserReferrals:input_type -> user.GetReferralsRequest
	9,  // 15: user.UserService.GetAdminMetrics:input_type -> user.AdminMetricsRequest
	11, // 16: user.UserService.BulkCreateUsers:input_type -> user.BulkCreateRequest
	5,  // 17: user.UserService.ExportUsers:input_type -> user.ListUsersRequest
	19, // 18: user.NotificationService.SendWelcomeEmail:input_type -> user.NotificationRequest
	19, // 19: user.NotificationService.SendNotification:input_type -> user.NotificationRequest
	14, // 20: user.AuthService.Login:output_type -> user.LoginResponse
	16, // 21: user.AuthService.ValidateToken:output_type -> user.AuthResponse
	14, // 22: user.AuthService.RefreshToken:output_type -> user.LoginResponse
	22, // 23: user.AuthService.Logout:output_type -> google.protobuf.Empty
	0,  // 24: user.UserService.CreateUser:output_type -> user.User
	0,  // 25: user.UserService.GetUser:output_type -> user.User
	0,  // 26: user.UserService.UpdateUser:output_type -> user.User
	22, // 27: user.UserService.DeleteUser:output_type -> google.protobuf.Empty
	6,  // 28: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	8,  // 29: user.UserService.GetUserReferrals:output_type -> user.GetReferralsResponse
	10, // 30: user.UserService.GetAdminMetrics:output_type -> user.AdminMetricsResponse
	12, // 31: user.UserService.BulkCreateUsers:output_type -> user.BulkCreateResponse
	0,  // 32: user.UserService.ExportUsers:output_type -> user.User
	20, // 33: user.NotificationService.SendWelcomeEmail:output_type -> user.NotificationResponse
	20, // 34: user.NotificationService.SendNotification:output_type -> user.NotificationResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_user_proto_init() }
func file_api_proto_user_proto_init() {
	if File_api_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_proto_rawDesc), len(file_api_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_proto_depIdxs,
		MessageInfos:      file_api_proto_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_proto = out.File
	file_api_proto_user_proto_goTypes = nil
	file_api_proto_user_proto_depIdxs = nil
}
